<a href="https://colab.research.google.com/github/daeunkk/dl11/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ch02_numpy.ipynb
 numpy 공부
 

In [ ]:
# chap02 - numpy
import numpy as np


In [8]:
import numpy as np

  # ndarray
a = np.array([1, 2, 3])

print(a[0])



1


In [ ]:


b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b

b[0][2]

In [7]:


a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

a.shape,a.ndim,a.dtype,a.itemsize,a.size


((3, 3), 2, dtype('int64'), 8, 9)

In [9]:
np.zeros( (3, 4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
	

np.ones( (3, 4), dtype=np.int32 )


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [11]:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:


x = np.ones(5, dtype=np.int64)

x

array([1, 1, 1, 1, 1])

In [13]:
print(np.arange(5))

print(np.arange(1, 6))

np.arange(1, 10, 2)

[0 1 2 3 4]
[1 2 3 4 5]


array([1, 3, 5, 7, 9])

In [14]:


np.linspace(0, 10, 100)


array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [15]:

# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:


# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])
x,y

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [17]:
#np.concatenate((x, y), axis=1)
#np.concatenate((x, y), axis=1)

#np.vstack((x, y))

np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [18]:


# reshape
a = np.arange(12)

a.shape

(12,)

In [22]:


# a.reshape(3, 4)

 #a.reshape(6, -1)
a.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:


array = np.arange(30).reshape(-1, 10)

array, array.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), (3, 10))

In [24]:
 

arr1, arr2 = np.split(array, [3], axis=1)

arr1,arr2

(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]]), array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19],
        [23, 24, 25, 26, 27, 28, 29]]))

In [25]:


# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [26]:


a1 = a[np.newaxis, :]

a1, a1.shape

(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [27]:


a2 = a[:, np.newaxis]

a2.shape


(6, 1)

###numpy-indexing&slicing

In [28]:

# indexing & slicing
ages = np.array([18, 19, 25, 30, 28])

ages[1:3], ages[:2] 

(array([19, 25]), array([18, 19]))

In [29]:
y = ages > 20

print(y)
#조건을 만족하는 데이터
ages[ ages > 20 ]

[False False  True  True  True]


array([25, 30, 28])

In [30]:
# 인덱싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 2])

a[0, 0] = 12

a

3


array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:


# 슬라이싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3]


array([[2, 3],
       [5, 6]])

###numpy연산
- elementwise operation
-vectorwise operation

In [32]:

# operation of arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[1, 1], [1, 1], [1, 1]])

result = arr1 + arr2

result

array([[2, 3],
       [4, 5],
       [6, 7]])

###브로드케스팅(broadcasting)

In [33]:


miles = np.array([1, 2, 3])

result = miles * 1.6

result

array([1.6, 3.2, 4.8])

In [34]:
#elementwise multiplication

arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 * arr2

result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [38]:
#vectorwise multiplication

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 @ arr2

result


array([[12, 12],
       [30, 30],
       [48, 48]])

In [35]:


A = np.array([0, 1, 2, 3])

10 * np.sin(A)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [36]:


a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a.sum(),a.min(),a.max()

(45, 1, 9)

In [37]:
a.argmin(),a.argmax()

(0, 8)

In [40]:


scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])    
scores.mean()
scores.mean(axis=1)
scores.mean(axis=0)

array([92.  , 80.5 , 78.75])

##무작위수 배열

In [47]:
# random numbers
np.random.seed(100)

# np.random.rand(5),np.random.rand(5)


# np.random.rand(5, 3)

# np.random.randn(5)

np.random.randn(5, 4)


array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

###[DIY]
- 컬러 이미지 100장을 무작위로 생성
- 이미지 크기는 28X28

In [48]:
image100 = np.random.randn(100, 28, 28, 3)
image100.shape

(100, 28, 28, 3)

In [49]:
m, sigma = 10, 2

m + sigma*np.random.randn(5)

array([ 8.12600727, 10.07239857,  8.639449  ,  8.44707082,  9.82908791])

In [50]:


mu, sigma = 0, 0.1 	# 평균과 표준 편차

np.random.normal(mu, sigma, 5)


array([ 0.00487541,  0.03221054, -0.07611538,  0.00467831, -0.03446541])

###np.unique()

In [53]:

# unique()
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
#a.size
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
uv, ui = np.unique(a, return_index=True)
uv,ui

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [59]:
uv, uc = np.unique(a, return_counts=True)
uv,uc

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [ ]:


# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


x.flatten()


pandas

In [ ]:

########################
# Pandas
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

########################
# matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()


import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()


X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()


import matplotlib.pyplot as plt 
import numpy as np 
  
X = np.linspace(-10, 10, 101) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 


import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 101) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 





